# Site settings
title: Your Site Title
description: A brief description of your site
baseurl: "" # If your site is hosted at https://username.github.io/repository/, set the baseurl to "/repository"

# Build settings
theme: jekyll-theme-hacker # Replace "jekyll-theme-name" with the name of your desired Jekyll theme

# Plugins
plugins:
  - jekyll-paginate # Uncomment this line if you want to enable pagination

# Pagination settings
paginate: 5 # Set the number of posts per page for pagination

# Navigation links
nav_links:
  - title: Home
    url: "/"
  - title: About
    url: "/about"
  - title: Blog
    url: "/blog"
  - title: Projects
    url: "/projects"

# Custom variables
custom_variable: value # Add any additional custom variables you want to use in your site

# Exclude files or folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore

# Markdown options
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  highlighter_opts:
    default_lang: ruby

# Other Jekyll configurations
# Add any additional Jekyll configurations specific to your theme or requirements
